### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by tensor-tian** [tensor-tian/code-note#13]
- [ ] tree graph
    - [ ] text block
    - [ ] scrolly block render ?
- [ ] flow graph 
    - [ ] label
    - [ ] layout like mermaid

**Comment by tensor-tian** [comment]
bugs:
- [ ] remove `Link` kind highlight. (need loop from reverse direction)
- [ ]  Parse mdx code `<Tooltip/>`throw an error , may prevent from recompile after the mdx code had been revised.
- [ ] mdx header bold style not work.

**Comment by tensor-tian** [comment]
use pnpm instead of yarn

**Comment by tensor-tian** [comment]
failed to draw Mark kind highlight
